from crossover import CrossOver
import numpy as np
import sys
sys.path.append('../problems')
from group import Group
from individual import Individual

class DECross(CrossOver):
    def __init__(self, firstParent, secondParent, co=0.8):
        """class ressponsible to handle crossover in DE cases

        Arguments:
            CrossOver {CrossOver} -- parent class
            firstParent {individuo} -- parent individuo
            secondParent {individuo} -- trial individuo generated by mutation

        Keyword Arguments:
            co {float} -- crossover probability by gene (default: {0.8})
        """
        CrossOver.__init__(self, "DE CrossOver", firstParent, secondParent) #First parent is Base Individuo and Second is Trial Vector
        self.co = co


    def make(self):
        """Cross over using DE binomial recombination

        Returns:
            individuo -- child individuo
        """
        chromosomeLen = len(self.firstParent.getChromosome())
        childChromosome = np.zeros(chromosomeLen)
        position = np.random.randint(chromosomeLen)
        for gene in range(chromosomeLen):
            if np.random.rand() < self.co or gene == position:
                childChromosome[gene] = self.secondParent.getChromosome()[gene]
            else:
                childChromosome[gene] = self.firstParent.getChromosome()[gene]

        child = Individual(childChromosome)

        return child
